name: "Disk Space Optimizer"
author: "hugoalh"
description: "Optimize disk space for GitHub hosted runner."
inputs:
  input_listdelimiter:
    description: "{RegEx} Delimiter when the input is accept list of values."
    required: false
    default: ",|;|\\r?\\n"
  operate_async:
    description: "[EXPERIMENTAL] {Boolean} Whether to operate in asynchronously to reduce the operation duration."
    required: false
    default: "False"
  operate_sudo:
    description: "{Boolean} Whether to execute this action in sudo mode on non-Windows environment."
    required: false
    default: "False"
  general_include:
    description: "{RegEx[]} Remove general item."
    required: false
    default: ""
  general_exclude:
    description: "{RegEx[]} Exclude remove general item."
    required: false
    default: ""
  docker_include:
    description: "{RegEx[]} Remove Docker image."
    required: false
    default: ""
  docker_exclude:
    description: "{RegEx[]} Exclude remove Docker image."
    required: false
    default: ""
  docker_prune:
    description: "{Boolean} Whether to prune Docker all of the dangling images."
    required: false
    default: "False"
  docker_clean:
    description: "{Boolean} Whether to remove Docker cache."
    required: false
    default: "False"
  apt_prune:
    description: "{Boolean} Whether to prune APT package."
    required: false
    default: "False"
  apt_clean:
    description: "{Boolean} Whether to remove APT cache."
    required: false
    default: "False"
  homebrew_prune:
    description: "{Boolean} Whether to prune Homebrew package."
    required: false
    default: "False"
  homebrew_clean:
    description: "{Boolean} Whether to remove Homebrew cache."
    required: false
    default: "False"
  npm_prune:
    description: "{Boolean} Whether to prune NPM package."
    required: false
    default: "False"
  npm_clean:
    description: "{Boolean} Whether to remove NPM cache."
    required: false
    default: "False"
  os_swap:
    description: "{Boolean} Whether to remove system page/swap file."
    required: false
    default: "False"
  dockerimage_include:
    description: "{RegEx[]} Remove Docker image."
    required: false
    deprecationMessage: "Replaced by input `docker_include`!"
  dockerimage_exclude:
    description: "{RegEx[]} Exclude remove Docker image."
    required: false
    deprecationMessage: "Replaced by input `docker_exclude`!"
  cache_apt:
    description: "{Boolean} Whether to remove APT cache."
    required: false
    deprecationMessage: "Replaced by inputs `apt_prune` and `apt_clean`!"
  cache_docker:
    description: "{Boolean} Whether to remove Docker cache."
    required: false
    deprecationMessage: "Replaced by inputs `docker_prune` and `docker_clean`!"
  cache_homebrew:
    description: "{Boolean} Whether to remove Homebrew cache."
    required: false
    deprecationMessage: "Replaced by inputs `homebrew_prune` and `homebrew_clean`!"
  cache_npm:
    description: "{Boolean} Whether to remove NPM cache."
    required: false
    deprecationMessage: "Replaced by inputs `npm_prune` and `npm_clean`!"
  swap:
    description: "{Boolean} Whether to remove Linux Swap Space."
    required: false
    deprecationMessage: "Replaced by input `os_swap`!"
runs:
  using: "composite"
  steps:
    - name: "Setup PowerShell Toolkit (Sudo)"
      if: "${{inputs.operate_sudo == 'True'}}"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.6.0"
      with:
        sudo: "${{inputs.operate_sudo}}"
        version: "^1.7.2"
        scope: "AllUsers"
        keepsetting: "False"
      continue-on-error: true
    - name: "Setup PowerShell Toolkit"
      if: "${{inputs.operate_sudo != 'True'}}"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.6.0"
      with:
        sudo: "${{inputs.operate_sudo}}"
        version: "^1.7.2"
        scope: "CurrentUsers"
        keepsetting: "False"
      continue-on-error: true
    - name: "Main"
      run: |
        #Requires -PSEdition Core -Version 7.2
        $Script:ErrorActionPreference = 'Stop'
        Get-Alias -Scope 'Local' -ErrorAction 'SilentlyContinue' |
          Remove-Alias -Scope 'Local' -Force -ErrorAction 'SilentlyContinue'
        Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
        Test-GitHubActionsEnvironment -Mandatory
        [String]$MainScriptPath = Join-Path -Path $Env:GITHUB_ACTION_PATH -ChildPath 'main.ps1'
        If (!(Test-Path -LiteralPath $MainScriptPath -PathType 'Leaf')) {
          Write-GitHubActionsFail -Message 'Invalid script path!'
        }
        [Boolean]$InputSudo = [Boolean]::Parse($Env:INPUT_OPERATE_SUDO)
        If ($InputSudo -and $Env:RUNNER_OS -iin @('Linux', 'MacOS')) {
          sudo --non-interactive --preserve-env pwsh -NonInteractive $MainScriptPath
        }
        Else {
          pwsh -NonInteractive $MainScriptPath
        }
      shell: "pwsh"
      env:
        INPUT_APT_CLEAN: "${{inputs.cache_apt || inputs.apt_clean}}"
        INPUT_APT_PRUNE: "${{inputs.cache_apt || inputs.apt_prune}}"
        INPUT_DOCKER_CLEAN: "${{inputs.cache_docker || inputs.docker_clean}}"
        INPUT_DOCKER_EXCLUDE: "${{inputs.dockerimage_exclude || inputs.docker_exclude}}"
        INPUT_DOCKER_INCLUDE: "${{inputs.dockerimage_include || inputs.docker_include}}"
        INPUT_DOCKER_PRUNE: "${{inputs.cache_docker || inputs.docker_prune}}"
        INPUT_GENERAL_EXCLUDE: "${{inputs.general_exclude}}"
        INPUT_GENERAL_INCLUDE: "${{inputs.general_include}}"
        INPUT_HOMEBREW_CLEAN: "${{inputs.cache_homebrew || inputs.homebrew_clean}}"
        INPUT_HOMEBREW_PRUNE: "${{inputs.cache_homebrew || inputs.homebrew_prune}}"
        INPUT_INPUT_LISTDELIMITER: "${{inputs.input_listdelimiter}}"
        INPUT_NPM_CLEAN: "${{inputs.cache_npm || inputs.npm_clean}}"
        INPUT_NPM_PRUNE: "${{inputs.cache_npm || inputs.npm_prune}}"
        INPUT_OPERATE_ASYNC: "${{inputs.operate_async}}"
        INPUT_OPERATE_SUDO: "${{inputs.operate_sudo}}"
        INPUT_OS_SWAP: "${{inputs.swap || inputs.os_swap}}"
      continue-on-error: true
    - name: "Setup PowerShell Toolkit (Sudo)"
      if: "${{inputs.operate_sudo == 'True'}}"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.6.0"
      with:
        sudo: "${{inputs.operate_sudo}}"
        version: "False"
        scope: "AllUsers"
        keepsetting: "False"
      continue-on-error: true
    - name: "Setup PowerShell Toolkit"
      if: "${{inputs.operate_sudo != 'True'}}"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.6.0"
      with:
        sudo: "${{inputs.operate_sudo}}"
        version: "False"
        scope: "CurrentUsers"
        keepsetting: "False"
      continue-on-error: true
branding:
  icon: "hard-drive"
  color: "green"
