name: "Disk Space Optimizer"
author: "hugoalh"
description: "Optimize disk space for GitHub hosted runner."
inputs:
  input_listdelimiter:
    description: "{RegEx} Delimiter when the input is type of list."
    required: false
    default: ",|;|\\r?\\n"
  operate_async:
    description: "{Boolean} Whether to operate in asynchronously to reduce the operation duration."
    required: false
    default: "False"
  general_include:
    description: "{RegEx[]} Remove general item."
    required: false
    default: ""
  general_exclude:
    description: "{RegEx[]} Exclude remove general item."
    required: false
    default: ""
  dockerimage_include:
    description: "{RegEx[]} Remove Docker image."
    required: false
    default: ""
  dockerimage_exclude:
    description: "{RegEx[]} Exclude remove Docker image."
    required: false
    default: ""
  cache_apt:
    description: "{Boolean} Whether to remove APT cache."
    required: false
    default: "False"
  cache_docker:
    description: "{Boolean} Whether to remove Docker cache."
    required: false
    default: "False"
  cache_homebrew:
    description: "{Boolean} Whether to remove Homebrew cache."
    required: false
    default: "False"
  cache_npm:
    description: "{Boolean} Whether to remove NPM cache."
    required: false
    default: "False"
  swap:
    description: "{Boolean} Whether to remove Linux Swap Space."
    required: false
    default: "False"
runs:
  using: "composite"
  steps:
    - name: "Setup PowerShell Toolkit"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.3.1"
    - name: "Main (Non-Windows)"
      if: "${{runner.os != 'Windows'}}"
      env:
        INPUT_CACHE_APT: "${{inputs.cache_apt}}"
        INPUT_CACHE_DOCKER: "${{inputs.cache_docker}}"
        INPUT_CACHE_HOMEBREW: "${{inputs.cache_homebrew}}"
        INPUT_CACHE_NPM: "${{inputs.cache_npm}}"
        INPUT_DOCKERIMAGE_EXCLUDE: "${{inputs.dockerimage_exclude}}"
        INPUT_DOCKERIMAGE_INCLUDE: "${{inputs.dockerimage_include}}"
        INPUT_GENERAL_EXCLUDE: "${{inputs.general_exclude}}"
        INPUT_GENERAL_INCLUDE: "${{inputs.general_include}}"
        INPUT_INPUT_LISTDELIMITER: "${{inputs.input_listdelimiter}}"
        INPUT_OPERATE_ASYNC: "${{inputs.operate_async}}"
        INPUT_SWAP: "${{inputs.swap}}"
      run: |
        sudo --non-interactive --preserve-env pwsh -NonInteractive "$GITHUB_ACTION_PATH/main.ps1"
      shell: "sh"
      continue-on-error: true
    - name: "Main (Windows)"
      if: "${{runner.os == 'Windows'}}"
      env:
        INPUT_CACHE_APT: "${{inputs.cache_apt}}"
        INPUT_CACHE_DOCKER: "${{inputs.cache_docker}}"
        INPUT_CACHE_HOMEBREW: "${{inputs.cache_homebrew}}"
        INPUT_CACHE_NPM: "${{inputs.cache_npm}}"
        INPUT_DOCKERIMAGE_EXCLUDE: "${{inputs.dockerimage_exclude}}"
        INPUT_DOCKERIMAGE_INCLUDE: "${{inputs.dockerimage_include}}"
        INPUT_GENERAL_EXCLUDE: "${{inputs.general_exclude}}"
        INPUT_GENERAL_INCLUDE: "${{inputs.general_include}}"
        INPUT_INPUT_LISTDELIMITER: "${{inputs.input_listdelimiter}}"
        INPUT_OPERATE_ASYNC: "${{inputs.operate_async}}"
        INPUT_SWAP: "${{inputs.swap}}"
      run: |
        pwsh -NonInteractive (Join-Path -Path $Env:GITHUB_ACTION_PATH -ChildPath 'main.ps1')
      shell: "pwsh"
      continue-on-error: true
branding:
  icon: "hard-drive"
  color: "green"
