# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Disk Space Optimizer"
author: "hugoalh"
description: "Optimize disk space for GitHub-hosted runner."
inputs:
  operate_async:
    description: "[EXPERIMENTAL] {boolean} Whether to operate in asynchronously to reduce the operation duration."
    required: false
    default: "false"
  operate_sudo:
    description: "{boolean} Whether to execute this action in sudo mode on non-Windows environment."
    required: false
    default: "false"
  general_include:
    description: "{RegEx[]} Remove general item."
    required: false
    default: ""
  general_exclude:
    description: "{RegEx[]} Exclude remove general item."
    required: false
    default: ""
  docker_include:
    description: "{RegEx[]} Remove Docker image."
    required: false
    default: ""
  docker_exclude:
    description: "{RegEx[]} Exclude remove Docker image."
    required: false
    default: ""
  docker_prune:
    description: "{boolean} Whether to prune Docker all of the dangling images."
    required: false
    default: "false"
  docker_clean:
    description: "{boolean} Whether to remove Docker cache."
    required: false
    default: "false"
  apt_enable:
    description: "{boolean} Whether to optimize via APT."
    required: false
    default: "false"
  apt_prune:
    description: "{boolean} Whether to prune APT package."
    required: false
    default: "false"
  apt_clean:
    description: "{boolean} Whether to remove APT cache."
    required: false
    default: "false"
  chocolatey_enable:
    description: "{boolean} Whether to optimize via Chocolatey."
    required: false
    default: "false"
  homebrew_enable:
    description: "{boolean} Whether to optimize via Homebrew."
    required: false
    default: "false"
  homebrew_prune:
    description: "{boolean} Whether to prune Homebrew package."
    required: false
    default: "false"
  homebrew_clean:
    description: "{boolean} Whether to remove Homebrew cache."
    required: false
    default: "false"
  npm_enable:
    description: "{boolean} Whether to optimize via NPM."
    required: false
    default: "false"
  npm_prune:
    description: "{boolean} Whether to prune NPM package."
    required: false
    default: "false"
  npm_clean:
    description: "{boolean} Whether to remove NPM cache."
    required: false
    default: "false"
  pipx_enable:
    description: "{boolean} Whether to optimize via Pipx."
    required: false
    default: "false"
  wmic_enable:
    description: "{boolean} Whether to optimize via WMIC."
    required: false
    default: "false"
  fs_enable:
    description: "{boolean} Whether to optimize via file system."
    required: false
    default: "false"
  os_swap:
    description: "{boolean} Whether to remove system page/swap file."
    required: false
    default: "false"
runs:
  using: "node20"
  pre: "dist/pre.js"
  main: "dist/main.js"
branding:
  icon: "hard-drive"
  color: "green"
