name: "Disk Space Optimizer"
author: "hugoalh"
description: "Optimize disk space for GitHub hosted runner."
inputs:
  input_listdelimiter:
    description: "{RegEx} Delimiter when the input is type of list."
    required: false
    default: ",|;|\\r?\\n"
  operate_async:
    description: "{Boolean} Whether to operate in asynchronously."
    required: false
    default: "False"
  general_include:
    description: "{RegEx[]} Remove general item."
    required: false
    default: ""
  general_exclude:
    description: "{RegEx[]} Exclude remove general item."
    required: false
    default: ""
  aptcache:
    description: "{Boolean} Whether to remove Linux APT (Advanced Packaging Tools) cache."
    required: false
    default: "False"
  dockerimage_include:
    description: "{RegEx[]} Remove Docker image."
    required: false
    default: ""
  dockerimage_exclude:
    description: "{RegEx[]} Exclude remove Docker image."
    required: false
    default: ""
  homebrewcache:
    description: "{Boolean} Whether to remove Homebrew cache."
    required: false
    default: "False"
  npmcache:
    description: "{Boolean} Whether to remove NPM (NodeJS Package Manager) cache."
    required: false
    default: "False"
  swap:
    description: "{Boolean} Whether to remove Linux Swap Space."
    required: false
    default: "False"
  general:
    description: "{RegEx[]} Remove general item."
    required: false
    default: ""
    deprecationMessage: "Use `general_include`!"
  dockerimage:
    description: "{RegEx[]} Remove Docker image."
    required: false
    default: ""
    deprecationMessage: "Use `dockerimage_include`!"
runs:
  using: "composite"
  steps:
    - name: "Setup PowerShell Toolkit"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.3.0"
      with:
        toolkit_version: "1.6.0-beta1"
        toolkit_allowprerelease: "True"
    - name: "Optimize Disk Space (Non-Windows)"
      if: "${{runner.os != 'Windows'}}"
      env:
        INPUT_INPUT_LISTDELIMITER: "${{inputs.input_listdelimiter}}"
        INPUT_OPERATE_ASYNC: "${{inputs.operate_async}}"
        INPUT_GENERAL: "${{inputs.general}}"
        INPUT_GENERAL_INCLUDE: "${{inputs.general_include}}"
        INPUT_GENERAL_EXCLUDE: "${{inputs.general_exclude}}"
        INPUT_APTCACHE: "${{inputs.aptcache}}"
        INPUT_DOCKERIMAGE: "${{inputs.dockerimage}}"
        INPUT_DOCKERIMAGE_INCLUDE: "${{inputs.dockerimage_include}}"
        INPUT_DOCKERIMAGE_EXCLUDE: "${{inputs.dockerimage_exclude}}"
        INPUT_HOMEBREWCACHE: "${{inputs.homebrewcache}}"
        INPUT_NPMCACHE: "${{inputs.npmcache}}"
        INPUT_SWAP: "${{inputs.swap}}"
      run: |
        sudo --non-interactive --preserve-env pwsh -NonInteractive "$GITHUB_ACTION_PATH/main.ps1"
      shell: "sh"
      continue-on-error: true
    - name: "Optimize Disk Space (Windows)"
      if: "${{runner.os == 'Windows'}}"
      env:
        INPUT_INPUT_LISTDELIMITER: "${{inputs.input_listdelimiter}}"
        INPUT_OPERATE_ASYNC: "${{inputs.operate_async}}"
        INPUT_GENERAL: "${{inputs.general}}"
        INPUT_GENERAL_INCLUDE: "${{inputs.general_include}}"
        INPUT_GENERAL_EXCLUDE: "${{inputs.general_exclude}}"
        INPUT_APTCACHE: "${{inputs.aptcache}}"
        INPUT_DOCKERIMAGE: "${{inputs.dockerimage}}"
        INPUT_DOCKERIMAGE_INCLUDE: "${{inputs.dockerimage_include}}"
        INPUT_DOCKERIMAGE_EXCLUDE: "${{inputs.dockerimage_exclude}}"
        INPUT_HOMEBREWCACHE: "${{inputs.homebrewcache}}"
        INPUT_NPMCACHE: "${{inputs.npmcache}}"
        INPUT_SWAP: "${{inputs.swap}}"
      run: |
        pwsh -NonInteractive (Join-Path -Path $Env:GITHUB_ACTION_PATH -ChildPath 'main.ps1')
      shell: "pwsh"
      continue-on-error: true
branding:
  icon: "hard-drive"
  color: "green"
